# File: templates/steps-common.yml

parameters:
    runExtendedTests: 'false'  # defaults for any parameters that aren't specified
    vmImage: ''

steps:
    - checkout: self
      submodules: recursive
    - script: |
        dotnet --list-runtimes
        dotnet --list-sdks
        dotnet --info
        dotnet --version
        msbuild -version
        ls -al
      displayName: 'Installation info'
    - task: DotNetCoreInstaller@0
      displayName: 'Use .NET Core SDK 2.2.105'
      inputs:
        version: '2.2.105'
    - task: DotNetCoreInstaller@0
      displayName: 'Use .NET Core SDK 3.0.100-preview3-010431'
      inputs:
        version: '3.0.100-preview3-010431'
    - script: |
        dotnet --list-runtimes
        dotnet --list-sdks
    - powershell: |
        dotnet tool install --tool-path ./tools --version 0.30.0 Cake.Tool
        ./tools/dotnet-cake --version
        $(Build.SourcesDirectory)/build.ps1
      workingDirectory: '$(Build.SourcesDirectory)' #
      displayName: Install Cake
    - ${{ if eq(parameters.runExtendedTests, 'true') }}:
        script: |
            dotnet --list-runtimes
            dotnet --list-sdks
            dotnet --info
            dotnet --version
            msbuild -version
        displayName: Test Installed Tools
    - powershell: |
        $(Build.SourcesDirectory)\build.ps1
        workingDirectory: '$(Build.SourcesDirectory)' #
        displayName: 'Execute Cake PowerShell Bootstrapper'
    - powershell: |
        .\build.ps1
        workingDirectory: '$(Build.SourcesDirectory)' #
        displayName: Run build .\build.ps1
    # - task: PublishTestResults@2
    #     displayName: Publish test results
    #     condition: always()
    #     inputs:
    #         testResultsFormat: xUnit
    #         testResultsFiles: tests/**/TestResults/TestResults.xml
    #         testRunTitle: Tests
